name: Continuous Integration

on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:
  schedule:
   - cron: '30 2 * * 1,4' # Every Monday and Thursday @ 2h30am UTC

env:
  USERNAME: sjperkins
  VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
  FEED_URL: https://nuget.pkg.github.com/sjperkins/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/sjperkins/index.json,readwrite"

jobs:
  vcpkg-nuget-test:
    name: Test vcpkg with nuget
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
    permissions:
      packages: write
    runs-on: ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v4

      # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@latest

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true


      # - name: Debug with tmate on failure
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3